export const franchiseMockSeed = [
  {
    _id: "1",
    name: "Sunria Agro Agro",
    state_id: "andhra_pradesh",
    state_name: "Andhra Pradesh",
    city_id: "vijayawada",
    city_name: "Vijayawada",
    area_id: ["benz_circle", "patamata", "governorpet"],
    area_name: ["Benz Circle", "MG Road", "Gandhi Hill"],
    admin_id: "admin_1",
    admin_name: "Ramesh",
    description: "Organic products franchise",
    desc: "Organic products franchise",
    desc2: "—",
    contact: "+91 9876543210",
    is_active: true,
  },
  {
    _id: "2",
    name: "Green Valley",
    state_id: "telangana",
    state_name: "Telangana",
    city_id: "hyderabad",
    city_name: "Hyderabad",
    area_id: ["madhapur", "hitech_city", "kukatpally"],
    area_name: ["Madhapur", "Hitech City", "Kukatpally"],
    admin_id: "admin_2",
    admin_name: "Suresh",
    description: "Grocery franchise outlet",
    desc: "Grocery franchise outlet",
    desc2: "—",
    contact: "+91 9876543211",
    is_active: false,
  },
  {
    _id: "3",
    name: "Organic Hub",
    state_id: "andhra_pradesh",
    state_name: "Andhra Pradesh",
    city_id: "visakhapatnam",
    city_name: "Visakhapatnam",
    area_id: ["mvp_colony", "maddilapalem", "seethammadhara"],
    area_name: ["MVP Colony", "Maddillapalem", "Isukathota"],
    admin_id: "admin_3",
    admin_name: "Mahesh",
    description: "Healthy food franchise",
    desc: "Healthy food franchise",
    desc2: "—",
    contact: "+91 9876543212",
    is_active: true,
  },
];

