import { AppConstant } from "../constant/AppConstant";
import type { UserModel } from "../models/UserModel";

/** Summary numbers shown on the Verification summary box when using mock data. */
export const MOCK_VERIFICATION_SUMMARY: Record<string, number> = {
    Total: 24,
    Pending: 9,
};

export type VerificationListFilters = {
    keyword?: string;
    status?: string;
};

/**
 * When `true`, the verification tab calls the real API (`/user/getVerificationAll`).
 * When `false`, the list and verification summary counts use local mock data (UI design only).
 * (Named without a `use` prefix so eslint `react-hooks/rules-of-hooks` does not treat this as a React hook.)
 */
export function shouldUseRealVerificationApi(): boolean {
    return AppConstant.USE_REAL_VERIFICATION_API !== false;
}

const MOCK_VERIFICATION_SOURCE: UserModel[] = [
    {
        _id: "mock-ver-001",
        name: "Asha Mehta",
        email: "asha.mehta@example.com",
        phone_number: "9876500001",
        address: "12 MG Road",
        landmark: null,
        state_id: "s1",
        city_id: "c1",
        state_name: "Karnataka",
        city_name: "Bengaluru",
        pincode: "560001",
        profile_url: null,
        user_id: "USR-MOCK-001",
        registration_id: "REG-2026-0001",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-01-10T08:00:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10001",
        verification_status: 1,
        submitted_at: "2026-02-01T10:15:00Z",
        verified_at: "",
        document_uploaded_count: 4,
    } as UserModel,
    {
        _id: "mock-ver-002",
        name: "Rahul Verma",
        email: "rahul.v@example.com",
        phone_number: "9876500002",
        address: "45 Park Street",
        landmark: null,
        state_id: "s2",
        city_id: "c2",
        state_name: "Maharashtra",
        city_name: "Mumbai",
        pincode: "400001",
        profile_url: null,
        user_id: "USR-MOCK-002",
        registration_id: "REG-2026-0002",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-01-12T09:00:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10002",
        verification_status: 2,
        submitted_at: "2026-02-03T14:20:00Z",
        verified_at: "",
        document_uploaded_count: 3,
    } as UserModel,
    {
        _id: "mock-ver-003",
        name: "Priya Nair",
        email: "priya.nair@example.com",
        phone_number: "9876500003",
        address: "78 Lake View",
        landmark: null,
        state_id: "s1",
        city_id: "c3",
        state_name: "Kerala",
        city_name: "Kochi",
        pincode: "682001",
        profile_url: null,
        user_id: "USR-MOCK-003",
        registration_id: "REG-2026-0003",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-01-15T11:30:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10003",
        verification_status: 3,
        submitted_at: "2026-02-05T09:00:00Z",
        verified_at: "2026-02-06T16:45:00Z",
        document_uploaded_count: 5,
    } as UserModel,
    {
        _id: "mock-ver-004",
        name: "Daniel Lee",
        email: "daniel.lee@example.com",
        phone_number: "9876500004",
        address: "90 High Street",
        landmark: null,
        state_id: "s3",
        city_id: "c4",
        state_name: "New South Wales",
        city_name: "Sydney",
        pincode: "2000",
        profile_url: null,
        user_id: "USR-MOCK-004",
        registration_id: "REG-2026-0004",
        is_from_web: true,
        is_active: false,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-01-18T07:45:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10004",
        verification_status: 1,
        submitted_at: "2026-02-08T12:00:00Z",
        verified_at: "",
        document_uploaded_count: 2,
    } as UserModel,
    {
        _id: "mock-ver-005",
        name: "Sneha Reddy",
        email: "sneha.reddy@example.com",
        phone_number: "9876500005",
        address: "3 Jubilee Hills",
        landmark: null,
        state_id: "s4",
        city_id: "c5",
        state_name: "Telangana",
        city_name: "Hyderabad",
        pincode: "500033",
        profile_url: null,
        user_id: "USR-MOCK-005",
        registration_id: "REG-2026-0005",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-01-20T10:00:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10005",
        verification_status: 2,
        submitted_at: "2026-02-10T08:30:00Z",
        verified_at: "",
        document_uploaded_count: 6,
    } as UserModel,
    {
        _id: "mock-ver-006",
        name: "James O'Brien",
        email: "james.obrien@example.com",
        phone_number: "9876500006",
        address: "22 Collins St",
        landmark: null,
        state_id: "s5",
        city_id: "c6",
        state_name: "Victoria",
        city_name: "Melbourne",
        pincode: "3000",
        profile_url: null,
        user_id: "USR-MOCK-006",
        registration_id: "REG-2026-0006",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-01-22T13:20:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10006",
        verification_status: 3,
        submitted_at: "2026-02-11T15:10:00Z",
        verified_at: "2026-02-12T09:30:00Z",
        document_uploaded_count: 4,
    } as UserModel,
    {
        _id: "mock-ver-007",
        name: "Kavita Singh",
        email: "kavita.singh@example.com",
        phone_number: "9876500007",
        address: "5 Civil Lines",
        landmark: null,
        state_id: "s6",
        city_id: "c7",
        state_name: "Delhi",
        city_name: "New Delhi",
        pincode: "110001",
        profile_url: null,
        user_id: "USR-MOCK-007",
        registration_id: "REG-2026-0007",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-01-25T09:40:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10007",
        verification_status: 1,
        submitted_at: "2026-02-14T11:25:00Z",
        verified_at: "",
        document_uploaded_count: 3,
    } as UserModel,
    {
        _id: "mock-ver-008",
        name: "Oliver Smith",
        email: "oliver.smith@example.com",
        phone_number: "9876500008",
        address: "40 George St",
        landmark: null,
        state_id: "s5",
        city_id: "c8",
        state_name: "Queensland",
        city_name: "Brisbane",
        pincode: "4000",
        profile_url: null,
        user_id: "USR-MOCK-008",
        registration_id: "REG-2026-0008",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-01-28T08:15:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10008",
        verification_status: 2,
        submitted_at: "2026-02-15T10:50:00Z",
        verified_at: "",
        document_uploaded_count: 5,
    } as UserModel,
    {
        _id: "mock-ver-009",
        name: "Meera Iyer",
        email: "meera.iyer@example.com",
        phone_number: "9876500009",
        address: "18 Anna Salai",
        landmark: null,
        state_id: "s7",
        city_id: "c9",
        state_name: "Tamil Nadu",
        city_name: "Chennai",
        pincode: "600002",
        profile_url: null,
        user_id: "USR-MOCK-009",
        registration_id: "REG-2026-0009",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-02-01T07:00:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10009",
        verification_status: 3,
        submitted_at: "2026-02-16T09:20:00Z",
        verified_at: "2026-02-17T14:00:00Z",
        document_uploaded_count: 4,
    } as UserModel,
    {
        _id: "mock-ver-010",
        name: "Hannah Wilson",
        email: "hannah.wilson@example.com",
        phone_number: "9876500010",
        address: "7 North Terrace",
        landmark: null,
        state_id: "s8",
        city_id: "c10",
        state_name: "South Australia",
        city_name: "Adelaide",
        pincode: "5000",
        profile_url: null,
        user_id: "USR-MOCK-010",
        registration_id: "REG-2026-0010",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-02-02T12:00:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10010",
        verification_status: 1,
        submitted_at: "2026-02-18T08:40:00Z",
        verified_at: "",
        document_uploaded_count: 2,
    } as UserModel,
    {
        _id: "mock-ver-011",
        name: "Vikram Joshi",
        email: "vikram.joshi@example.com",
        phone_number: "9876500011",
        address: "33 FC Road",
        landmark: null,
        state_id: "s2",
        city_id: "c11",
        state_name: "Maharashtra",
        city_name: "Pune",
        pincode: "411004",
        profile_url: null,
        user_id: "USR-MOCK-011",
        registration_id: "REG-2026-0011",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-02-04T09:10:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10011",
        verification_status: 2,
        submitted_at: "2026-02-19T13:15:00Z",
        verified_at: "",
        document_uploaded_count: 6,
    } as UserModel,
    {
        _id: "mock-ver-012",
        name: "Emma Taylor",
        email: "emma.taylor@example.com",
        phone_number: "9876500012",
        address: "2 Barrack St",
        landmark: null,
        state_id: "s9",
        city_id: "c12",
        state_name: "Western Australia",
        city_name: "Perth",
        pincode: "6000",
        profile_url: null,
        user_id: "USR-MOCK-012",
        registration_id: "REG-2026-0012",
        is_from_web: true,
        is_active: true,
        is_business: false,
        type: 2,
        registration_type: null,
        device_token: null,
        platform_type: 1,
        business_info_id: null,
        auth_token: null,
        created_by_id: null,
        last_signin: null,
        password: null,
        current_password: null,
        new_password: null,
        confirm_password: null,
        deleted_at: null,
        created_at: "2026-02-06T10:30:00Z",
        updated_at: null,
        total_amount: 0,
        total_payment: 0,
        paid_amount: 0,
        balance_amount: null,
        received_payment: 0,
        in_progress_payment: 0,
        refund_payment: 0,
        payment_mode: null,
        last_paid_date: null,
        last_service_date: null,
        total_service: 0,
        service_paid: 0,
        service_unpaid: 0,
        in_progress_service: 0,
        completed_service: 0,
        cancelled_service: 0,
        my_services: [],
        bank_account: null,
        documents: [],
        verification_id: "VER-10012",
        verification_status: 3,
        submitted_at: "2026-02-20T07:55:00Z",
        verified_at: "2026-02-21T11:10:00Z",
        document_uploaded_count: 5,
    } as UserModel,
];

/**
 * Partner-style verification preview dialog: load user from mock data only (no `fetchUserById` / HTTP).
 * Unknown ids get a shallow clone of the first mock row with the requested `_id`.
 */
export function getMockVerificationUserById(id: string): UserModel {
    const found = MOCK_VERIFICATION_SOURCE.find((r) => r._id === id);
    if (found) {
        return { ...found, documents: Array.isArray(found.documents) ? [...found.documents] : [] };
    }
    const template = MOCK_VERIFICATION_SOURCE[0];
    return {
        ...template,
        _id: id,
        name: "Sample partner (mock)",
        email: "sample.partner@example.com",
        phone_number: "9000000000",
        address: "12 Sample Street, Demo City",
        registration_id: "REG-MOCK-0000",
        documents: [],
    } as UserModel;
}

function filterMockVerificationRows(filters: VerificationListFilters): UserModel[] {
    let rows = [...MOCK_VERIFICATION_SOURCE];
    const kw = filters.keyword?.trim().toLowerCase();
    if (kw) {
        rows = rows.filter(
            (r) =>
                (r.name && r.name.toLowerCase().includes(kw)) ||
                (r.registration_id && r.registration_id.toLowerCase().includes(kw)) ||
                (r.verification_id && String(r.verification_id).toLowerCase().includes(kw))
        );
    }
    const st = filters.status;
    if (st && st !== "All") {
        const wantActive = st.toLowerCase() === "true";
        rows = rows.filter((r) => Boolean(r.is_active) === wantActive);
    }
    return rows;
}

export function getMockVerificationListPage(
    page: number,
    pageSize: number,
    filters: VerificationListFilters
): { response: boolean; users: UserModel[]; totalPages: number } {
    const filtered = filterMockVerificationRows(filters);
    const total = filtered.length;
    if (total === 0) {
        return { response: true, users: [], totalPages: 0 };
    }
    const totalPages = Math.ceil(total / pageSize);
    const safePage = Math.min(Math.max(1, page), totalPages);
    const start = (safePage - 1) * pageSize;
    const users = filtered.slice(start, start + pageSize);
    return {
        response: true,
        users,
        totalPages,
    };
}
