export const ApiPaths = {
  LOGIN: () => `/auth/login`,
  FORGOT_PASSWORD: () => `/auth/forgotPassword`,
  LOGOUT: () => `/auth/logout`,
  SEND_OTP: () => `/otp/send-otp`,
  VERIFY_OTP: () => `/otp/verify-otp`,
  GET_COUNT: '/getCount',
  GET_USER_BY_ID: () => `/user/get`,
  CREATE_USER: '/user/create',
  GET_USER: () => `/user/getAll`,
  GET_USER_DROP_DOWN: () => `/user/getDropDown`,
  UPDATE_USER: (id: string) => `/user/update/${id}`,
  DELETE_USER: (id: string) => `/user/delete/${id}`,
  CHANGE_PASSWORD: '/user/changePassword',
  GET_VERIFICATION: '/document_upload/files',
  DOCUMENT_UPLOAD: '/document_upload/files',
  UPDATE_DOCUMENT_UPLOAD: '/document_upload/update_files',
  GET_STATE: () => `/state/getAll`,
  GET_STATE_DROP_DOWN: () => `/state/getDropDown`,
  CREATE_STATE: '/state/create',
  UPDATE_STATE: (id: string) => `/state/update/${id}`,
  DELETE_STATE: (id: string) => `/state/delete/${id}`,
  GET_CITY: () => `/city/getAll`,
  GET_CITY_DROP_DOWN: () => `/city/getDropDown`,
  CREATE_CITY: '/city/create',
  UPDATE_CITY: (id: string) => `/city/update/${id}`,
  DELETE_CITY: (id: string) => `/city/delete/${id}`,
  GET_CATEGORY: () => `/category/getAll`,
  GET_CATEGORY_DROP_DOWN: () => `/category/getDropDown`,
  CREATE_CATEGORY: '/category/create',
  UPDATE_CATEGORY: (id: string) => `/category/update/${id}`,
  DELETE_CATEGORY: (id: string) => `/category/delete/${id}`,
  GET_SERVICE: () => `/service/getAll`,
  GET_SERVICE_DROP_DOWN: () => `/service/getDropDown`,
  CREATE_SERVICE: '/service/create',
  UPDATE_SERVICE: (id: string) => `/service/update/${id}`,
  DELETE_SERVICE: (id: string) => `/service/delete/${id}`,
  CREATE_BANK_ACCOUNT: '/bank_account/create',
  UPDATE_BANK_ACCOUNT: (id: string) => `/bank_account/update/${id}`,
  UPDATE_PARTNER_DOCUMENT: (id: string) => `/partner_document/updateDocument/${id}`,
};
